/** All user-facing text (docs/PLAN.md §10), ready for localisation (T6.09). */
export const STRINGS = {
  title: 'Tidepool',
  play: 'Play',
  continue: 'Continue',
  voyage: 'Voyage',
  comingSoon: 'soon',
  score: 'Score',
  best: 'Best',
  pause: 'Pause',
  gameOver: 'Out of room',
  newBest: 'New best!',
  playAgain: 'Play again',
  menu: 'Menu',
  secondChance: 'Watch an ad to keep going',
  paused: 'Paused',
  resume: 'Resume',
  restart: 'Restart',
  restartConfirm: 'Start over? This run will end.',
  cancel: 'Cancel',
  settings: 'Settings',
  back: 'Back',
  sound: 'Sound',
  music: 'Music',
  haptics: 'Vibration',
  palette: 'Colours',
  paletteDefault: 'Tidepool',
  paletteColorblind: 'Colour-blind friendly',
  patterns: 'Shape patterns',
  reducedMotion: 'Reduce motion',
  lowPower: 'Battery saver',
  resetProgress: 'Reset progress',
  resetConfirm1: 'Erase your best score, stats and saved run?',
  resetYes: 'Yes, erase',
  resetConfirm2: "This can't be undone.",
  resetFinal: 'Erase everything',
  privacy: 'Privacy',
  credits: 'Credits',
  creditsText:
    'Design, code, graphics and sound: made for Tidepool. All sounds and visuals are generated in code.',
  streak: (multiplier: number) => `×${multiplier}`,
  callouts: {
    nice: 'Nice!',
    splash: 'Splash!',
    tidalWave: 'Tidal Wave!',
    crystalClear: 'Crystal Clear!',
  },
} as const;
