/**
 * Offline support for PWA targets (T3.08, docs/PLAN.md §20): links the web manifest and emits
 * `sw.js`, a service worker that precaches exactly this build's files. It is a small
 * purpose-built plugin rather than a dependency: the game is one page with hashed assets.
 */
import type { Plugin } from 'vite';

/** Public files every PWA build precaches alongside the bundle. */
export const PUBLIC_PRECACHE = [
  './',
  'manifest.webmanifest',
  'privacy.html',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/maskable-512.png',
  'icons/apple-touch-icon.png',
];

/** The service worker source for a cache name and file list. */
export function serviceWorkerSource(cacheName: string, files: readonly string[]): string {
  return `// Generated by tools/pwa-plugin.ts. Cache-first for this build's files; updates wait
// until the game says so (the "New version" toast), so a run is never reloaded by surprise.
const CACHE = ${JSON.stringify(cacheName)};
const FILES = ${JSON.stringify(files)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
    ).then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith(
    // ignoreVary: module scripts send an Origin header the precache requests didn't.
    caches.match(request, { ignoreSearch: request.mode === 'navigate', ignoreVary: true }).then(
      (hit) =>
        hit ||
        fetch(request).catch(() =>
          request.mode === 'navigate' ? caches.match('./') : Response.error(),
        ),
    ),
  );
});
`;
}

export function pwaPlugin(enabled: boolean, version: string): Plugin {
  return {
    name: 'tidepool-pwa',
    apply: 'build',
    transformIndexHtml: () =>
      enabled
        ? [
            {
              tag: 'link',
              attrs: { rel: 'manifest', href: 'manifest.webmanifest' },
              injectTo: 'head',
            },
            {
              tag: 'link',
              attrs: { rel: 'apple-touch-icon', href: 'icons/apple-touch-icon.png' },
              injectTo: 'head',
            },
          ]
        : [],
    generateBundle(_options, bundle) {
      if (!enabled) return;
      const files = [...PUBLIC_PRECACHE, ...Object.keys(bundle).filter((f) => !f.endsWith('.map'))];
      // The cache name changes whenever any file name (content hash) does.
      const hash = files
        .join('|')
        .split('')
        .reduce((h, ch) => (Math.imul(h, 31) + ch.charCodeAt(0)) | 0, 7)
        .toString(36);
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: serviceWorkerSource(`tidepool-${version}-${hash}`, files),
      });
    },
  };
}
